<?php
$_brandCollection = $block->getBrandCollection();

// Boostrap Carousel
$itemsperpage = 12;
//$lg_column_item = (int)$this->getConfig('brand_list_page/lg_column_item',6);
//$md_column_item = (int)$this->getConfig('brand_list_page/md_column_item',6);
//$sm_column_item = (int)$this->getConfig('brand_list_page/sm_column_item',4);
//$xs_column_item = (int)$this->getConfig('brand_list_page/xs_column_item',2);
$lg_column_item = 8;
$md_column_item = 6;
$sm_column_item = 4;
$xs_column_item = 2;

//$show_brand_name = $this->getConfig('brand_list_page/show_brand_name');
$lg_column = 12/$lg_column_item;
$md_column = 12/$md_column_item;
$sm_column = 12/$sm_column_item;
$xs_column = 12/$xs_column_item;
$i = 1;
$x = 0;
?>
<?php if ($_brandCollection->count()) { ?>
    <?php $total = $_brandCollection->count(); ?>
    <div class="brandlist" style="margin-top: 50px;">
        <div class="block-content">
            <?php foreach ($_brandCollection as $_brand) { ?>
                <?php if ($lg_column_item == 1 || $x%$lg_column_item == 0) { ?>
                    <!-- ROW -->
                    <div class="row">
                <?php } ?>
                <div class="col-lg-<?php echo $lg_column ?> col-md-<?php echo $md_column ?> col-sm-<?php echo $sm_column ?> col-xs-<?php echo $xs_column ?>" style="margin: 15px;">
                    <div class="brand-item">
                        <div class="brand-image"><a href="<?= $_brand->getUrl(); ?>"><img width="200" height="70" src="<?php echo $_brand->getThumbnailUrl(); ?>"/></a></div>
                        <div class="brand-name" style="text-align: center; margin: 10px;"><a href="<?= $_brand->getUrl() ?>" title="<?php echo $_brand->getName(); ?>"><?php echo $_brand->getName() ?></a></div>
                    </div>
                </div>
                <?php if ($lg_column_item == 1 || ($x+1)%$lg_column_item == 0 || $i == $total) {  ?>
                    </div><!-- ROW -->
                <?php } ?>
                <?php $i++; $x++; ?>
            <?php } ?>
        </div>
        <?php if ($block->getPagerHtml()): ?>
            <div class="order-products-toolbar toolbar bottom" style="margin-top: 50px;"><?php echo $block->getPagerHtml(); ?></div>
        <?php endif ?>
    </div>
<?php } ?>
