<?php
$helper = $this->helper("Smartosc\Brand\Helper\Data");
?>
<div class="smartosc-block block brand-searchform">
    <div class="block-title">
        <strong><?php echo __('Search Brand'); ?></strong>
    </div>
    <div class="block-content">
        <form method="get" class="search-form" action="<?php echo $helper->getSearchFormUrl(); ?>">
            <input type="text" class="search-field required-entry" placeholder="<?php echo __('Search brands here…'); ?>" value="<?php echo $helper->getSearchKey() ?>" name="s" title="<?php echo __('Search for:'); ?>" style="width: 70%"/>
            <button type="submit" class="search-submit"><i class="fa fa-search">go</i></button>
        </form>
    </div>
</div>
