<?php
$_brandCollection = $block->getBrandCollection();
$firstchar_arr = $block->groupBrandByFirstChar();
$groupid = $block->getParam();
$alphanum = $block->getAlphaNumeric();
$lg_column_item = 8;
$md_column_item = 6;
$sm_column_item = 4;
$xs_column_item = 2;

$lg_column = 12/$lg_column_item;
$md_column = 12/$md_column_item;
$sm_column = 12/$sm_column_item;
$xs_column = 12/$xs_column_item;
$i = 1;
$x = 0;
?>
<div class="title"><h4>Shop By Brand Group</h4></div>
<div class="pagination">
    <a href="<?= $block->getBrandListUrl(); ?>"  style="margin: 5px;" <?php if ($groupid == "") { ?> class = "active" <?php } ?> >All</a>
    <?php foreach ($alphanum as $letter) { ?>
        <?php if (array_search($letter, $block->groupBrandByFirstChar()) === false) { ?>
            <a class="disable" style="margin: 5px; background-color: grey; color: white; border: 1px solid grey;"> <?php echo ($letter === "00") ? "0" : $letter; ?></a>
        <?php } elseif ($letter == $groupid && $groupid != "") { ?>
            <a class="active" href="<?= $block->getGroupUrl($letter); ?>"   style="margin: 5px;"> <?php echo ($letter === "00") ? "0" : $letter; ?></a>
        <?php } else { ?>
    <a href="<?= $block->getGroupUrl($letter); ?>"  style="margin: 5px;"><?php echo ($letter === "00") ? "0" : $letter; ?></a>
            <?php } ?>
    <?php } ?>
</div>

<?php if ($_brandCollection->count()) { ?>
    <?php $total = $_brandCollection->count(); ?>
    <div class="brandlist" style="margin-top: 50px;">
        <div class="block-content">
            <?php foreach ($_brandCollection as $_brand) { ?>
                <?php if ($lg_column_item == 1 || $x%$lg_column_item == 0) { ?>
                    <!-- ROW -->
                    <div class="row">
                <?php } ?>
                <div class="col-lg-<?php echo $lg_column ?> col-md-<?php echo $md_column ?> col-sm-<?php echo $sm_column ?> col-xs-<?php echo $xs_column ?>" style="margin: 15px;">
                    <div class="brand-item">
                        <div class="brand-image"><a href="<?= $_brand->getUrl(); ?>"><img width="200" height="70" src="<?php echo $_brand->getThumbnailUrl(); ?>"/></a></div>
                        <div class="brand-name" style="text-align: center; margin: 10px;"><a href="<?= $_brand->getUrl() ?>" title="<?php echo $_brand->getName(); ?>"><?php echo $_brand->getName() ?></a></div>
                    </div>
                </div>
                <?php if ($lg_column_item == 1 || ($x+1)%$lg_column_item == 0 || $i == $total) {  ?>
                    </div><!-- ROW -->
                <?php } ?>
                <?php $i++; $x++; ?>
            <?php } ?>
        </div>
        <?php if ($block->getPagerHtml()): ?>
            <div class="order-products-toolbar toolbar bottom" style="margin-top: 50px;"><?php echo $block->getPagerHtml(); ?></div>
        <?php endif ?>
    </div>
<?php } ?>
