<?php
$brandCollection = $this->getBrandCollection();
$brand_text = __('Brands: ');

?>
<?php if ($brandCollection && $brandCollection->count()) { ?>
    <?php
    $i = 0;
    $total = $brandCollection->count();
        echo '<span class="brand-label">' . $brand_text . '</span>';
        echo '<ul class="product-brands">';
        foreach ($brandCollection as $_brand) {
            ?>
            <li class="brand-item">
                <h3><a href="<?php echo $_brand->getUrl(); ?>" title="<?php echo $_brand->getName(); ?>"><?php echo $_brand->getName(); ?></a></h3><br/>
                <a href="<?php echo $_brand->getUrl(); ?>" title="<?php echo $_brand->getName(); ?>">
                        <img width="100" height="40" src="<?php echo $_brand->getThumbnailUrl(); ?>" alt="<?php echo $_brand->getName(); ?>"/></a>
                <?php
                    $_description = $_brand->getDescription(); ?>
                    <div class="brand-description">
                      <small> <?php echo $this->helper('Smartosc\Brand\Helper\Data')->filter($_description) ?></small>
                    </div>
            </li>
            <?php
        } ?>
            </ul>
            <?php
    }
    ?>

